baseURL = "http://arttuv.com/"
languageCode = "en"
title = "arttuv"
theme = "whiteplain"

publishDir = "docs"

[params]

	pygmentsstyle = "rainbow_dash"
	# Analytics
	googleAnalytics = "UA-101290596-1"

	[params.author]
	name = "Arttu Viljakainen"
	# Gravatar or Abatar image
	gravatar = "arttu.viljakainen@gmail.com"
	twitter = "arttuv"
	linkedin = "www.linkedin.com/in/arttu-viljakainen"
	email = "arttu.viljakainen@gmail.com"

[taxonomies]
	category = "categories"
	tag = "tags"
	series = "series"

# Header Menu
[[menu.main]]
	name = "Categories"
	identifier = "categories"
	url = "/categories/"
	weight = 1
	[[menu.main]]
	name = "Tags"
	identifier = "tags"
	url = "/tags/"
	weight = 2
	[[menu.main]]
	[[menu.main]]
	name = "About"
	identifier = "about"
	url = "/about/"
	weight = 3

# Footer Menu
[[menu.footer]]
	name = "About"
	weight = 1
	identifier = "about"
	url = "/about/"