baseURL = "http://arttuv.com/"
languageCode = "en-us"
title = "arttuv"
publishDir = "docs"

[taxonomies]
	tag = "tags"
	category = "categories"

[params]

	pygmentsstyle = "rainbow_dash"
	# Analytics
	googleAnalytics = "UA-101290596-1"

	# Include favicon
	favicon = "favicon.ico"
 
	# Email (optional)
	email = "arttu.viljakainen@gmail.com"
	
	# Header Title for the main page
	header = "Writings"
	
	# Sidebar profile picture
	profilepic = "img/smugmug.jpg"
	
	# Title/subtitle for the sidebar
	title = "Arttu Viljakainen"
	subtitle = "UX Oriented software engineer"
	
	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "github"
	url = ""
	[[params.socialbuttons]]
	faicon = "twitter"
	url = ""
	[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://linkedin.com"
	[[params.socialbuttons]]
	faicon = "google-plus"
	url = "https://plus.google.com/+YourID"

	# Nav links below the profile picture
	[[params.navlinks]]
	name = "About"
	url = "about/"
	